import org.antlr.v4.runtime.tree.ParseTreeVisitor;
import org.antlr.v4.runtime.*;
import org.antlr.v4.runtime.tree.*;
import org.antlr.v4.runtime.CharStreams;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

public class main {
    public static void main(String[] args) throws IOException {

        // we expect exactly one argument: the name of the input file
        if (args.length != 1) {
            System.err.println("\n");
            System.err.println("Hardware Interpreter\n");
            System.err.println("=================\n\n");
            System.err.println("Please give as input argument a filename\n");
            System.exit(-1);
        }
        String filename = args[0];

        // open the input file
        CharStream input = CharStreams.fromFileName(filename);
        //new ANTLRFileStream (filename); // depricated

        // create a lexer/scanner
        hardwareLexer lex = new hardwareLexer(input);

        // get the stream of tokens from the scanner
        CommonTokenStream tokens = new CommonTokenStream(lex);

        // create a parser
        hardwareParser parser = new hardwareParser(tokens);

        // and parse anything from the grammar for "start"
        ParseTree parseTree = parser.start();

        // Construct an interpreter and run it on the parse tree
        Interpreter interpreter = new Interpreter();
        Command result=(Command)interpreter.visit(parseTree);
        //System.out.println("The result is: "+
        result.eval(new Environment());
    }
}

// We write an interpreter that implements interface
// "hardwareVisitor<T>" that is automatically generated by ANTLR
// This is parameterized over a return type "<T>" which is in our case
// shardwarey a Integer.

class Interpreter extends AbstractParseTreeVisitor<AST> implements hardwareVisitor<AST> {

    @Override
    public AST visitStart(hardwareParser.StartContext ctx) {
        return visit(ctx.cs);
    }

    @Override
    public AST visitSequence(hardwareParser.SequenceContext ctx) {
        return new Sequence((Command)visit(ctx.c),(Command)visit(ctx.cs));
    }

    @Override
    public AST visitNOP(hardwareParser.NOPContext ctx) {
        return new NOP();
    }

    @Override
    public AST visitHardware(hardwareParser.HardwareContext ctx) {
        return null;
    }

    @Override
    public AST visitInputs(hardwareParser.InputsContext ctx) {
        return null;
    }

    @Override
    public AST visitOutputs(hardwareParser.OutputsContext ctx) {
        return null;
    }

    @Override
    public AST visitLatches(hardwareParser.LatchesContext ctx) {
        return null;
    }

    @Override
    public AST visitUpdate(hardwareParser.UpdateContext ctx) {
        return null;
    }

    @Override
    public AST visitSimulate(hardwareParser.SimulateContext ctx) {
        return null;
    }

    @Override
    public AST visitLatchDeclaration(hardwareParser.LatchDeclarationContext ctx) {
        return null;
    }

    @Override
    public AST visitUpdateDeclaration(hardwareParser.UpdateDeclarationContext ctx) {
        return null;
    }

    @Override
    public AST visitIdentifier(hardwareParser.IdentifierContext ctx) {
        return new Identifier(ctx.id.getText());
    }

    @Override
    public AST visitOr(hardwareParser.OrContext ctx) {
        return new Or((Expr)visit(ctx.e1), (Expr)visit(ctx.e2));
    }

    @Override
    public AST visitNegation(hardwareParser.NegationContext ctx) {
        return new Negation((Expr)visit(ctx.e));
    }

    @Override
    public AST visitAnd(hardwareParser.AndContext ctx) {
        return new And((Expr)visit(ctx.e1), (Expr)visit(ctx.e2));
    }

    @Override
    public AST visitParentheses(hardwareParser.ParenthesesContext ctx) {
        return new Parantheses((Parantheses)visit(ctx.e));
    }

    @Override
    public AST visitSimulation(hardwareParser.SimulationContext ctx) {
        return null;
    }

    /*
    // From lecture 4.

    public Expr visitStart(hardwareParser.StartContext ctx) {
        return visit(ctx.e);
    }

    public Expr visitMultiplication(hardwareParser.MultiplicationContext ctx) {
        if (ctx.op.getText().equals("*"))
            return new Multiplication(visit(ctx.e1), visit(ctx.e2));
        else
            return new Division(visit(ctx.e1), visit(ctx.e2));
    }

    public Expr visitAddition(hardwareParser.AdditionContext ctx) {
        if (ctx.op.getText().equals("+"))
            return new Addition(visit(ctx.e1), visit(ctx.e2));
        else
            return new Subtraction(visit(ctx.e1), visit(ctx.e2));
    }

    public Expr visitVariable(hardwareParser.VariableContext ctx) {
        return new Variable(ctx.x.getText());
    }

    public Expr visitConstant(hardwareParser.ConstantContext ctx) {
        return new Constant(Integer.parseInt(ctx.c.getText()));
    }

    public Expr visitParentheses(hardwareParser.ParenthesesContext ctx) {
        return visit(ctx.e1);
    }
    */
}

